# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# Spring Application
# ===============================
spring.application.name=customer-service

# ===============================
# Datasource (H2 - local dev)
# ===============================
spring.datasource.url=jdbc:h2:mem:customerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console