# ===============================
# Server
# ===============================
server.port=8082

# ===============================
# Spring Application
# ===============================
spring.application.name=account-service

# ===============================
# Datasource (H2 - local dev)
# ===============================
spring.datasource.url=jdbc:h2:mem:accountdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# Datasource (PostgreSQL)
# ===============================
# spring.datasource.url=jdbc:postgresql://localhost:5432/accountdb
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# AWS SQS Configuration
# ===============================
aws.sqs.queue.transaction-events=transaction-events-queue

# SQS does NOT create queues automatically
spring.cloud.aws.sqs.listener.auto-create=false
spring.cloud.aws.sqs.queue-auto-create=false
